"""
Analyze E2 circuit density logs and generate scaling/overhead plots.

This script consumes logs generated by e2_circuit_density.py and produces:
1) Torbox vs Tor overhead vs node scale.
2) Tail build-time (p95/p99) vs node scale for Tor and Torbox.

Defaults assume logs live at exp/deployment/e2_density/logs/<mode>/<relay_tier>.
"""
from __future__ import annotations
import numpy as np
import matplotlib.pyplot as plt
from scipy.interpolate import PchipInterpolator
import argparse
import json
import math
import re
from dataclasses import dataclass
from pathlib import Path
from typing import Dict, Iterable, List, Optional

import matplotlib.pyplot as plt


@dataclass
class RunSummary:
    mode_tag: str
    relay_tier: str
    concurrency: Optional[int]
    total_mean_ms: Optional[float]
    total_p95_ms: Optional[float]
    total_p99_ms: Optional[float]
    build_mean_ms: Optional[float]
    build_p50_ms: Optional[float]
    build_p95_ms: Optional[float]
    build_p99_ms: Optional[float]
    cpu_total_ms: Optional[float]
    peak_mem_mb: Optional[float]
    success_rate: Optional[float]
    samples_ok: int
    source: Path


def _percentile(values: List[float], pct: float) -> Optional[float]:
    if not values:
        return None
    pct = max(0.0, min(100.0, pct))
    ordered = sorted(values)
    pos = (len(ordered) - 1) * pct / 100.0
    lower = math.floor(pos)
    upper = math.ceil(pos)
    if lower == upper:
        return ordered[int(pos)]
    low_val = ordered[lower]
    high_val = ordered[upper]
    return low_val + (high_val - low_val) * (pos - lower)


def _mean(values: List[float]) -> Optional[float]:
    return sum(values) / len(values) if values else None


def _load_jsonl(dir_path: Path) -> List[dict]:
    records: List[dict] = []
    if not dir_path.exists():
        return records
    for file in sorted(dir_path.glob("*.jsonl")):
        with file.open("r", encoding="utf-8") as f:
            for line in f:
                line = line.strip()
                if not line:
                    continue
                try:
                    records.append(json.loads(line))
                except json.JSONDecodeError:
                    continue
    return records


def _normalize_log_dir(meta_path: Path, meta: dict) -> Path:
    log_dir = meta.get("log_dir")
    if log_dir:
        return Path(log_dir)
    return meta_path.parent


def _sort_tiers(tiers: Iterable[str]) -> List[str]:
    def key(label: str) -> float:
        match = re.search(r"(\d+(?:\.\d+)?)", label)
        return float(match.group(1)) if match else float("inf")

    return sorted(set(tiers), key=key)


def summarize_run(meta_path: Path) -> Optional[RunSummary]:
    try:
        meta = json.loads(meta_path.read_text(encoding="utf-8"))
    except Exception:
        return None

    log_dir = _normalize_log_dir(meta_path, meta)
    circuits = _load_jsonl(log_dir / "circuits")
    resources = _load_jsonl(log_dir / "resources")
    if not circuits:
        return None

    mode_tag = str(meta.get("mode_tag") or meta_path.parent.parent.name)
    relay_tier = str(meta.get("relay_tier") or meta_path.parent.name)
    concurrency = meta.get("concurrency")

    measurement = [
        c for c in circuits
        if c.get("event") == "circuit_attempt" and c.get("phase") == "measure"
    ]
    ok = [c for c in measurement if c.get("status") == "ok"]
    fail = [c for c in measurement if c.get("status") == "fail"]
    denom = len(ok) + len(fail)
    success_rate = len(ok) / denom if denom else None

    total_ms = [float(c.get("latency_ms", 0.0)) for c in ok if "latency_ms" in c]
    build_ms = [float(c.get("build_ms", 0.0)) for c in ok if c.get("build_ms") is not None]

    cpu_total_candidates = [
        float(r.get("total_cpu_ms", 0.0))
        for r in resources
        if isinstance(r.get("total_cpu_ms"), (int, float))
    ]
    if not cpu_total_candidates:
        cpu_total_candidates = [
            float(r.get("local_cpu_ms_from_start", 0.0))
            for r in resources
            if isinstance(r.get("local_cpu_ms_from_start"), (int, float))
        ]
    cpu_total_ms = max(cpu_total_candidates) if cpu_total_candidates else None

    peak_mem_candidates = [
        float(r.get("total_mem_mb", 0.0))
        for r in resources
        if isinstance(r.get("total_mem_mb"), (int, float))
    ]
    if not peak_mem_candidates:
        peak_mem_candidates = [
            float(r.get("local_rss_mb", 0.0))
            for r in resources
            if isinstance(r.get("local_rss_mb"), (int, float))
        ]
    peak_mem_mb = max(peak_mem_candidates) if peak_mem_candidates else None

    return RunSummary(
        mode_tag=mode_tag,
        relay_tier=relay_tier,
        concurrency=concurrency,
        total_mean_ms=_mean(total_ms),
        total_p95_ms=_percentile(total_ms, 95),
        total_p99_ms=_percentile(total_ms, 99),
        build_mean_ms=_mean(build_ms),
        build_p50_ms=_percentile(build_ms, 50),
        build_p95_ms=_percentile(build_ms, 95),
        build_p99_ms=_percentile(build_ms, 99),
        cpu_total_ms=cpu_total_ms,
        peak_mem_mb=peak_mem_mb,
        success_rate=success_rate,
        samples_ok=len(ok),
        source=meta_path,
    )


def discover_runs(root: Path, explicit_meta: Iterable[Path]) -> List[RunSummary]:
    runs: List[RunSummary] = []
    if explicit_meta:
        for meta in explicit_meta:
            meta_path = meta if meta.name == "run_meta.json" else meta / "run_meta.json"
            rec = summarize_run(meta_path)
            if rec:
                runs.append(rec)
        return runs

    for meta_path in root.rglob("run_meta.json"):
        rec = summarize_run(meta_path)
        if rec:
            runs.append(rec)
    return runs


def write_summary_csv(out_dir: Path, runs: List[RunSummary]) -> Path:
    out_path = out_dir / "density_summary.csv"
    headers = [
        "mode_tag",
        "relay_tier",
        "concurrency",
        "samples_ok",
        "success_rate",
        "total_mean_ms",
        "total_p95_ms",
        "total_p99_ms",
        "build_mean_ms",
        "build_p50_ms",
        "build_p95_ms",
        "build_p99_ms",
        "cpu_total_ms",
        "peak_mem_mb",
        "source",
    ]
    lines = [",".join(headers)]
    for run in runs:
        values = [
            run.mode_tag,
            run.relay_tier,
            "" if run.concurrency is None else str(run.concurrency),
            str(run.samples_ok),
            "" if run.success_rate is None else f"{run.success_rate:.4f}",
            "" if run.total_mean_ms is None else f"{run.total_mean_ms:.3f}",
            "" if run.total_p95_ms is None else f"{run.total_p95_ms:.3f}",
            "" if run.total_p99_ms is None else f"{run.total_p99_ms:.3f}",
            "" if run.build_mean_ms is None else f"{run.build_mean_ms:.3f}",
            "" if run.build_p50_ms is None else f"{run.build_p50_ms:.3f}",
            "" if run.build_p95_ms is None else f"{run.build_p95_ms:.3f}",
            "" if run.build_p99_ms is None else f"{run.build_p99_ms:.3f}",
            "" if run.cpu_total_ms is None else f"{run.cpu_total_ms:.3f}",
            "" if run.peak_mem_mb is None else f"{run.peak_mem_mb:.3f}",
            str(run.source),
        ]
        lines.append(",".join(values))
    out_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return out_path


def write_overhead_csv(out_dir: Path, runs: List[RunSummary]) -> Path:
    out_path = out_dir / "density_overhead.csv"
    by_mode: Dict[str, Dict[str, RunSummary]] = {}
    for run in runs:
        by_mode.setdefault(run.mode_tag, {})[run.relay_tier] = run

    tiers = _sort_tiers(
        set(by_mode.get("tor", {}).keys()) | set(by_mode.get("torbox", {}).keys())
    )
    headers = [
        "relay_tier",
        "tor_total_mean_ms",
        "torbox_total_mean_ms",
        "total_overhead_pct",
        "tor_build_mean_ms",
        "torbox_build_mean_ms",
        "build_overhead_pct",
    ]
    lines = [",".join(headers)]
    for tier in tiers:
        tor = by_mode.get("tor", {}).get(tier)
        torbox = by_mode.get("torbox", {}).get(tier)

        tor_total = tor.total_mean_ms if tor else None
        torbox_total = torbox.total_mean_ms if torbox else None
        tor_build = tor.build_mean_ms if tor else None
        torbox_build = torbox.build_mean_ms if torbox else None

        total_overhead = None
        if tor_total and torbox_total and tor_total > 0:
            total_overhead = (torbox_total - tor_total) / tor_total * 100.0

        build_overhead = None
        if tor_build and torbox_build and tor_build > 0:
            build_overhead = (torbox_build - tor_build) / tor_build * 100.0

        lines.append(",".join([
            tier,
            "" if tor_total is None else f"{tor_total:.3f}",
            "" if torbox_total is None else f"{torbox_total:.3f}",
            "" if total_overhead is None else f"{total_overhead:.2f}",
            "" if tor_build is None else f"{tor_build:.3f}",
            "" if torbox_build is None else f"{torbox_build:.3f}",
            "" if build_overhead is None else f"{build_overhead:.2f}",
        ]))
    out_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return out_path


def plot_overhead(out_dir: Path, runs: List[RunSummary]) -> Optional[Path]:
    by_mode: Dict[str, Dict[str, RunSummary]] = {}
    for run in runs:
        by_mode.setdefault(run.mode_tag, {})[run.relay_tier] = run

    tiers = _sort_tiers(
        set(by_mode.get("tor", {}).keys()) | set(by_mode.get("torbox", {}).keys())
    )
    if not tiers:
        return None

    x = []
    overhead = []
    for tier in tiers:
        tor = by_mode.get("tor", {}).get(tier)
        torbox = by_mode.get("torbox", {}).get(tier)
        if not tor or not torbox:
            continue
        if not tor.total_mean_ms or tor.total_mean_ms <= 0:
            continue
        x.append(tier)
        overhead.append((torbox.total_mean_ms - tor.total_mean_ms) / tor.total_mean_ms * 100.0)

    if not x:
        return None

    fig, ax = plt.subplots(figsize=(8, 5))
    ax.plot(x, overhead, marker="o", label="Torbox vs Tor (mean total latency)")
    ax.set_xlabel("Relay tier (node scale)")
    ax.set_ylabel("Overhead (%)")
    ax.set_title("Torbox performance overhead vs node scale")
    ax.grid(True, linestyle="--", alpha=0.3)
    ax.legend()

    out_path = out_dir / "torbox_overhead.png"
    fig.tight_layout()
    fig.savefig(out_path, dpi=160)
    plt.close(fig)
    return out_path


def plot_tail_build(out_dir: Path, runs: List[RunSummary]) -> Optional[Path]:
    by_mode: Dict[str, Dict[str, RunSummary]] = {}
    for run in runs:
        by_mode.setdefault(run.mode_tag, {})[run.relay_tier] = run

    tiers = _sort_tiers(
        set(by_mode.get("tor", {}).keys()) | set(by_mode.get("torbox", {}).keys())
    )
    if not tiers:
        return None

    def collect(mode: str, field: str) -> List[Optional[float]]:
        return [getattr(by_mode.get(mode, {}).get(tier), field, None) for tier in tiers]

    tor_p95 = collect("tor", "build_p95_ms")
    tor_p99 = collect("tor", "build_p99_ms")
    torbox_p95 = collect("torbox", "build_p95_ms")
    torbox_p99 = collect("torbox", "build_p99_ms")

    fig, ax = plt.subplots(figsize=(8, 5))
    ax.plot(tiers, tor_p95, marker="o", label="Tor build p95")
    ax.plot(tiers, tor_p99, marker="o", linestyle="--", label="Tor build p99")
    ax.plot(tiers, torbox_p95, marker="s", label="Torbox build p95")
    ax.plot(tiers, torbox_p99, marker="s", linestyle="--", label="Torbox build p99")

    ax.set_xlabel("Relay tier (node scale)")
    ax.set_ylabel("Build time (ms)")
    ax.set_title("Tail build-time vs node scale (p95/p99)")
    ax.grid(True, linestyle="--", alpha=0.3)
    ax.legend()

    out_path = out_dir / "build_tail_p95_p99.png"
    fig.tight_layout()
    fig.savefig(out_path, dpi=160)
    plt.close(fig)
    return out_path


def plot_total_resources(out_dir: Path, runs: List[RunSummary]) -> Optional[Path]:
    by_mode: Dict[str, Dict[str, RunSummary]] = {}
    for run in runs:
        by_mode.setdefault(run.mode_tag, {})[run.relay_tier] = run

    tiers = _sort_tiers(
        set(by_mode.get("tor", {}).keys()) | set(by_mode.get("torbox", {}).keys())
    )
    if not tiers:
        return None

    def collect(mode: str) -> List[Optional[float]]:
        return [getattr(by_mode.get(mode, {}).get(tier), "cpu_total_ms", None) for tier in tiers]

    tor_cpu = collect("tor")
    torbox_cpu = collect("torbox")

    fig, ax = plt.subplots(figsize=(8, 5))
    ax.plot(tiers, tor_cpu, marker="o", label="Tor total CPU (ms)")
    ax.plot(tiers, torbox_cpu, marker="s", label="Torbox total CPU (ms)")

    ax.set_xlabel("Relay tier (node scale)")
    ax.set_ylabel("Total resource overhead (CPU ms)")
    ax.set_title("Total resource overhead vs node scale")
    ax.grid(True, linestyle="--", alpha=0.3)
    ax.legend()

    out_path = out_dir / "total_resource_overhead.png"
    fig.tight_layout()
    fig.savefig(out_path, dpi=160)
    plt.close(fig)
    return out_path


def plot_total_memory(out_dir: Path, runs: List[RunSummary]) -> Optional[Path]:
    # --- 1. 数据提取与清洗 ---
    by_mode: Dict[str, Dict[str, RunSummary]] = {}
    for run in runs:
        by_mode.setdefault(run.mode_tag, {})[run.relay_tier] = run

    tiers = _sort_tiers(
        set(by_mode.get("tor", {}).keys()) | set(by_mode.get("torbox", {}).keys())
    )
    if not tiers:
        return None

    def collect(mode: str) -> List[Optional[float]]:
        return [getattr(by_mode.get(mode, {}).get(tier), "peak_mem_mb", None) for tier in tiers]

    tor_mem = collect("tor")
    torbox_mem = collect("torbox")

    # X轴数值化：尝试将 "10", "20" 转为数字，以保证横轴比例真实
    try:
        x_numeric = np.array([float(t) for t in tiers])
        is_numeric_x = True
    except ValueError:
        x_numeric = np.arange(len(tiers))
        is_numeric_x = False

    def clean_xy(y_data):
        valid_idx = [i for i, v in enumerate(y_data) if v is not None]
        return x_numeric[valid_idx], np.array([y_data[i] for i in valid_idx])

    x_tor, y_tor = clean_xy(tor_mem)
    x_torbox, y_torbox = clean_xy(torbox_mem)

    # --- 2. 论文级绘图设置 ---

    # 字体配置：优先使用 Arial/Helvetica 等无衬线字体，清晰度高
    plt.rcParams['font.family'] = 'sans-serif'
    plt.rcParams['font.sans-serif'] = ['Arial', 'DejaVu Sans', 'Helvetica', 'sans-serif']

    # 画布大小：(8, 5) 是一个适合插入论文的标准比例
    fig, ax = plt.subplots(figsize=(8, 5))

    # 配色方案：高对比度，科研常用色 (深蓝 vs 砖红)
    # 这种配色在转为灰度图时灰度值差异也较大，便于识别
    c_tor = '#0072B2'  # Blue
    c_torbox = '#D55E00'  # Vermilion (Red-Orange)

    # --- 3. 绘制折线 (保持真实数据，不做插值) ---

    # Tor 线条
    ax.plot(x_tor, y_tor,
            marker='o',  # 圆形标记
            markersize=8,  # 标记大小：适中，缩放后依然可见
            linewidth=2.0,  # 线宽：2.0 打印清晰
            color=c_tor,
            label="Tor",  # 简化图例标签，去掉 "Peak Memory" 冗余词
            markeredgecolor='white',  # 白边提升对比度
            markeredgewidth=1.5,
            zorder=3)

    # Torbox 线条
    ax.plot(x_torbox, y_torbox,
            marker='s',  # 方形标记 (形状不同，便于黑白区分)
            markersize=8,
            linewidth=2.0,
            color=c_torbox,
            label="Torbox",
            markeredgecolor='white',
            markeredgewidth=1.5,
            zorder=3)

    # --- 4. 样式精修 ---

    # 坐标轴标签：字号 14，加粗
    ax.set_xlabel("Relay Tier (Node Scale)", fontsize=14, fontweight='bold', labelpad=8)
    ax.set_ylabel("Peak Memory (MB)", fontsize=14, fontweight='bold', labelpad=8)

    # 刻度标签：字号 12
    ax.tick_params(axis='both', which='major', labelsize=12, width=1.2, length=5)

    # 还原 X 轴的文本标签 (如果是数值轴)
    if is_numeric_x:
        ax.set_xticks(x_numeric)
        ax.set_xticklabels(tiers)

    # Y 轴范围：从 0 开始，顶部留出 10% 空间
    y_max = max(np.max(y_tor) if len(y_tor) else 0, np.max(y_torbox) if len(y_torbox) else 0)
    ax.set_ylim(0, y_max * 1.1)

    # 边框处理：典型的学术图表风格（去掉上、右边框）
    ax.spines['top'].set_visible(False)
    ax.spines['right'].set_visible(False)
    ax.spines['left'].set_linewidth(1.2)
    ax.spines['bottom'].set_linewidth(1.2)

    # 网格线：仅保留横向，灰色虚线，透明度低，位于底层
    ax.yaxis.grid(True, linestyle='--', color='gray', alpha=0.3, zorder=0)
    ax.xaxis.grid(False)

    # 图例：去框，字号 12，放在左上角
    ax.legend(frameon=False, fontsize=12, loc='upper left')

    # 保存配置
    out_path = out_dir / "total_memory_overhead.png"

    # tight_layout 确保文字不被裁剪
    fig.tight_layout()

    # dpi=300 是印刷出版的标准分辨率
    fig.savefig(out_path, dpi=300, bbox_inches='tight')
    plt.close(fig)

    return out_path



def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Analyze E2 circuit density logs for scaling and tail latency.",
    )
    parser.add_argument(
        "--log-root",
        type=Path,
        default=Path("exp") / "deployment" / "e2_density" / "logs",
        help="Root directory containing mode_tag/relay_tier/run_meta.json",
    )
    parser.add_argument(
        "--out-dir",
        type=Path,
        default=Path("exp") / "deployment" / "e2_density" / "analysis",
        help="Directory to store CSV summaries and plots",
    )
    parser.add_argument(
        "--meta",
        type=Path,
        nargs="*",
        default=[],
        help="Optional explicit run_meta.json paths",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    runs = discover_runs(args.log_root, args.meta)
    if not runs:
        print("No runs discovered. Check --log-root or --meta paths.")
        return

    args.out_dir.mkdir(parents=True, exist_ok=True)
    summary_csv = write_summary_csv(args.out_dir, runs)
    overhead_csv = write_overhead_csv(args.out_dir, runs)
    overhead_plot = plot_overhead(args.out_dir, runs)
    tail_plot = plot_tail_build(args.out_dir, runs)
    resource_plot = plot_total_resources(args.out_dir, runs)
    memory_plot = plot_total_memory(args.out_dir, runs)

    print(f"Summary CSV: {summary_csv}")
    print(f"Overhead CSV: {overhead_csv}")
    if overhead_plot:
        print(f"Overhead plot: {overhead_plot}")
    if tail_plot:
        print(f"Tail build-time plot: {tail_plot}")
    if resource_plot:
        print(f"Total resource plot: {resource_plot}")
    if memory_plot:
        print(f"Total memory plot: {memory_plot}")


if __name__ == "__main__":
    main()