"""Single-user single-circuit semantic validation runner.

This wrapper normalises environment variables for a deterministic run and
prints the JSONL output paths generated by :mod:`client_runner`.
"""

import asyncio
import json
import os
from pathlib import Path

import client_runner


def _set_defaults():
    os.environ.setdefault("CLIENTS_PER_BATCH", "1")
    os.environ.setdefault("TOTAL_BATCHES", "1")
    os.environ.setdefault("BATCH_DELAY", "0")
    os.environ.setdefault("HOPS", "3")
    os.environ.setdefault("PAYLOAD_MB", "10")
    os.environ.setdefault("CHUNK_KB", "32")
    os.environ.setdefault("WARMUP_KB", "4")
    os.environ.setdefault("START_TIMEOUT_S", "30")
    os.environ.setdefault("INTER_CHUNK_SLEEP_MS", "0")


async def _run_once():
    _set_defaults()
    meta_path = await client_runner.main()

    try:
        meta = json.loads(meta_path.read_text(encoding="utf-8"))
    except Exception:
        meta = None

    print(f"[SemanticRunner] run metadata: {meta_path}")
    if meta and meta.get("log_files"):
        events_path = meta["log_files"].get("events")
        print(f"[SemanticRunner] events JSONL: {events_path}")
    return meta_path


def run():
    meta_path = asyncio.run(_run_once())
    return meta_path


if __name__ == "__main__":
    run()