"""Single-user single-circuit semantic validation runner.

This wrapper normalises environment variables for a deterministic run and
prints the JSONL output paths generated by :mod:`client_runner`.
"""

import asyncio
import json
import os
from pathlib import Path

import client_runner


def _set_defaults():
    os.environ.setdefault("CLIENTS_PER_BATCH", "1")
    os.environ.setdefault("TOTAL_BATCHES", "5")
    os.environ.setdefault("BATCH_DELAY", "0")
    os.environ.setdefault("HOPS", "3")
    os.environ.setdefault("PAYLOAD_MB", "10")
    os.environ.setdefault("CHUNK_KB", "32")
    os.environ.setdefault("WARMUP_KB", "4")
    os.environ.setdefault("START_TIMEOUT_S", "30")
    os.environ.setdefault("INTER_CHUNK_SLEEP_MS", "0")
    os.environ.setdefault("LOG_DIR", "exp/semantic_logs/torbox")
    os.environ.setdefault("EXP_LABEL", "torbox")
    # os.environ.setdefault("LOG_DIR", "exp/semantic_logs/tor")
    # os.environ.setdefault("EXP_LABEL", "tor")


async def _run_once():
    _set_defaults()
    meta_path = await client_runner.main()

    try:
        meta = json.loads(meta_path.read_text(encoding="utf-8"))
    except Exception:
        meta = None

    print(f"[SemanticRunner] run metadata: {meta_path}")
    if meta and meta.get("log_files"):
        events_path = meta["log_files"].get("events")
        print(f"[SemanticRunner] events JSONL: {events_path}")
    return meta_path


async def _run_multi_rounds():
    rounds = int(os.environ.get("RUN_ROUNDS", "1"))
    base_dir_env = os.environ.get("LOG_DIR", "exp/semantic_logs")
    base_dir = Path(base_dir_env)

    meta_paths = []
    for idx in range(rounds):
        if rounds > 1:
            round_dir = base_dir / f"round_{idx:03d}"
            os.environ["LOG_DIR"] = str(round_dir)
            print(f"[SemanticRunner] round {idx + 1}/{rounds} -> LOG_DIR={round_dir}")
        else:
            round_dir = base_dir
            os.environ["LOG_DIR"] = str(round_dir)

        meta_paths.append(await _run_once())

    manifest = base_dir / "multi_run_manifest.json"
    manifest.parent.mkdir(parents=True, exist_ok=True)
    manifest.write_text(
        json.dumps(
            {
                "rounds": rounds,
                "meta_paths": [str(p) for p in meta_paths],
            },
            indent=2,
        ),
        encoding="utf-8",
    )
    print(f"[SemanticRunner] manifest written to {manifest}")
    return meta_paths

def run():
    return asyncio.run(_run_multi_rounds())

if __name__ == "__main__":
    run()